/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        emerald: "var(--emerald)",
        "emerald-light": "var(--emerald-light)",
        "blue-accent": "var(--blue-accent)",
        "cyan-accent": "var(--cyan-accent)",
        "neon-green": "var(--neon-green)",
        "neon-red": "var(--neon-red)",
        "neon-yellow": "var(--neon-yellow)",
        "neon-gold": "var(--neon-gold)",
        "slate-dark": "var(--slate-dark)",
        "slate-medium": "var(--slate-medium)",
        "severity-low": "var(--severity-low)",
        "severity-medium": "var(--severity-medium)",
        "severity-high": "var(--severity-high)",
        "severity-critical": "var(--severity-critical)",
        "chart-1": "var(--chart-1)",
        "chart-2": "var(--chart-2)",
        "chart-3": "var(--chart-3)",
        "chart-4": "var(--chart-4)",
        "chart-5": "var(--chart-5)",
        sidebar: "var(--sidebar)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        "sidebar-primary": "var(--sidebar-primary)",
        "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
        "sidebar-accent": "var(--sidebar-accent)",
        "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "sidebar-border": "var(--sidebar-border)",
        "sidebar-ring": "var(--sidebar-ring)",
      },
      fontFamily: {
        sans: ["Inter", "Inter Fallback", "sans-serif"],
        mono: ["JetBrains Mono", "JetBrains Mono Fallback", "monospace"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "calc(var(--radius) + 4px)",
      },
      animation: {
        'scan': 'scan 2.5s ease-in-out infinite',
      },
      keyframes: {
        scan: {
          '0%, 100%': { transform: 'translateY(0vh)' },
          '50%': { transform: 'translateY(80vh)' },
        }
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
}